[project]
requires-python = ">= 3.9"

[tool.poetry]
name = "clp-package-utils"
version = "0.5.2-dev"
description = "Utilities for the CLP package."
authors = ["YScope Inc. <dev@yscope.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">= 3.9"
Brotli = "^1.1.0"
msgpack = "^1.0.7"
psutil = "^7.1.0"
pydantic = "^2.11.9"
pymongo = "^4.7.2"
PyYAML = "^6.0.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

