[tool.poetry]
name = "compression-job-handler"
version = "0.1.0"
description = "Component for submitting compression jobs to CLP."
authors = ["YScope Inc. <dev@yscope.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8 || ^3.10"
celery = "^5.3.4"
pymongo = "^4.5.0"

[tool.poetry.group.dev.dependencies]
black = "^23.9.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
