apiVersion: "v1"
kind: "Service"
metadata:
  name: {{ include "clp-package.fullname" . }}-api-server
  labels:
    {{- include "clp-package.labels" . | nindent 4 }}
    app.kubernetes.io/component: "api-server"
spec:
  type: "NodePort"
  selector:
    {{- include "clp-package.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: "api-server"
  ports:
    - port: 3001
      targetPort: "http"
      nodePort: {{ .Values.clpConfig.api_server.port }}
---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: {{ include "clp-package.fullname" . }}-api-server
  labels:
    {{- include "clp-package.labels" . | nindent 4 }}
    app.kubernetes.io/component: "api-server"
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "clp-package.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: "api-server"
  template:
    metadata:
      labels:
        {{- include "clp-package.labels" . | nindent 8 }}
        app.kubernetes.io/component: "api-server"
    spec:
      terminationGracePeriodSeconds: 10
      securityContext:
        runAsUser: {{ .Values.securityContext.firstParty.uid }}
        runAsGroup: {{ .Values.securityContext.firstParty.gid }}
        fsGroup: {{ .Values.securityContext.firstParty.gid }}
      initContainers:
        - name: "wait-for-database"
          image: "busybox:latest"
          command: [
            "sh", "-c",
            "until nc -z {{ include "clp-package.fullname" . }}-database 3306; do echo waiting for database; sleep 2; done"
          ]
        - name: "wait-for-results-cache"
          image: "busybox:latest"
          command: [
            "sh", "-c",
            "until nc -z {{ include "clp-package.fullname" . }}-results-cache 27017; do echo waiting for results-cache; sleep 2; done"
          ]
      containers:
        - name: "api-server"
          image: "{{ include "clp-package.image.ref" . }}"
          imagePullPolicy: "Always"
          env:
            - name: "CLP_DB_USER"
              valueFrom:
                secretKeyRef:
                  name: {{ include "clp-package.fullname" . }}-secret
                  key: "db-username"
            - name: "CLP_DB_PASS"
              valueFrom:
                secretKeyRef:
                  name: {{ include "clp-package.fullname" . }}-secret
                  key: "db-password"
            - name: "CLP_LOGS_DIR"
              value: "/var/log/api_server"
            - name: "RUST_LOG"
              value: "DEBUG"
          ports:
            - name: "http"
              containerPort: 3001
          volumeMounts:
            - name: "config"
              mountPath: "/etc/clp-config.yml"
              subPath: "clp-config.yml"
              readOnly: true
            - name: "api-server-logs"
              mountPath: "/var/log/api_server"
          command: [
            "/opt/clp/bin/api_server",
            "--host", "0.0.0.0",
            "--port", "3001",
            "--config", "/etc/clp-config.yml"
          ]
          livenessProbe:
            {{- include "clp-package.livenessProbeTimings" . | nindent 12 }}
            httpGet:
              path: "/health"
              port: 3001
          readinessProbe:
            {{- include "clp-package.readinessProbeTimings" . | nindent 12 }}
            httpGet:
              path: "/health"
              port: 3001
      volumes:
        - name: "config"
          configMap:
            name: {{ include "clp-package.fullname" . }}-config
        - name: "api-server-logs"
          persistentVolumeClaim:
            claimName: {{ include "clp-package.fullname" . }}-api-server-logs
---
apiVersion: "v1"
kind: "PersistentVolumeClaim"
metadata:
  name: {{ include "clp-package.fullname" . }}-api-server-logs
  labels:
    {{- include "clp-package.labels" . | nindent 4 }}
    app.kubernetes.io/component: "api-server"
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: "local-storage"
  selector:
    matchLabels:
      {{- include "clp-package.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: "api-server"
  resources:
    requests:
      storage: "5Gi"
