apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: {{ include "clp.fullname" . }}-api-server
  labels:
    {{- include "clp.labels" . | nindent 4 }}
    app.kubernetes.io/component: "api-server"
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "clp.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: "api-server"
  template:
    metadata:
      labels:
        {{- include "clp.labels" . | nindent 8 }}
        app.kubernetes.io/component: "api-server"
    spec:
      terminationGracePeriodSeconds: 10
      securityContext:
        runAsUser: {{ .Values.securityContext.firstParty.uid }}
        runAsGroup: {{ .Values.securityContext.firstParty.gid }}
        fsGroup: {{ .Values.securityContext.firstParty.gid }}
      initContainers:
        - name: "wait-for-database"
          image: "busybox:latest"
          command:
            - "sh"
            - "-c"
            - >-
              until nc -z {{ include "clp.fullname" . }}-database 3306;
                do echo Waiting for database to be ready...;
                sleep 2;
              done
        - name: "wait-for-results-cache"
          image: "busybox:latest"
          command:
            - "sh"
            - "-c"
            - >-
              until nc -z {{ include "clp.fullname" . }}-results-cache 27017;
                do echo Waiting for results-cache to be ready...;
                sleep 2;
              done
      containers:
        - name: "api-server"
          image: "{{ include "clp.image.ref" . }}"
          imagePullPolicy: "{{ .Values.image.clpPackage.pullPolicy }}"
          env:
            - name: "CLP_DB_USER"
              valueFrom:
                secretKeyRef:
                  name: {{ include "clp.fullname" . }}-database
                  key: "username"
            - name: "CLP_DB_PASS"
              valueFrom:
                secretKeyRef:
                  name: {{ include "clp.fullname" . }}-database
                  key: "password"
            - name: "CLP_LOGS_DIR"
              value: "/var/log/api_server"
            - name: "RUST_LOG"
              value: "DEBUG"
          ports:
            - name: "api-server"
              containerPort: 3001
          volumeMounts:
            - name: "config"
              mountPath: "/etc/clp-config.yaml"
              subPath: "clp-config.yaml"
              readOnly: true
            - name: "api-server-logs"
              mountPath: "/var/log/api_server"
          command: [
            "/opt/clp/bin/api_server",
            "--host", "0.0.0.0",
            "--port", "3001",
            "--config", "/etc/clp-config.yaml"
          ]
          readinessProbe:
            {{- include "clp.readinessProbeTimings" . | nindent 12 }}
            httpGet: &api-server-health-check
              path: "/health"
              port: 3001
          livenessProbe:
            {{- include "clp.livenessProbeTimings" . | nindent 12 }}
            httpGet: *api-server-health-check
      volumes:
        - name: "config"
          configMap:
            name: {{ include "clp.fullname" . }}-config
        - name: "api-server-logs"
          persistentVolumeClaim:
            claimName: {{ include "clp.fullname" . }}-api-server-logs
