{{- if and .Values.clpConfig.api_server (ne .Values.clpConfig.package.query_engine "presto") }}
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: {{ include "clp.fullname" . }}-api-server
  labels:
    {{- include "clp.labels" . | nindent 4 }}
    app.kubernetes.io/component: "api-server"
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "clp.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: "api-server"
  template:
    metadata:
      labels:
        {{- include "clp.labels" . | nindent 8 }}
        app.kubernetes.io/component: "api-server"
    spec:
      serviceAccountName: {{ include "clp.fullname" . }}-job-watcher
      terminationGracePeriodSeconds: 60
      securityContext:
        runAsUser: {{ .Values.securityContext.firstParty.uid }}
        runAsGroup: {{ .Values.securityContext.firstParty.gid }}
        fsGroup: {{ .Values.securityContext.firstParty.gid }}
      initContainers:
        - {{- include "clp.waitFor" (dict
            "root" .
            "type" "job"
            "name" "db-table-creator"
          ) | nindent 10 }}
        - {{- include "clp.waitFor" (dict
            "root" .
            "type" "job"
            "name" "results-cache-indices-creator"
          ) | nindent 10 }}
      containers:
        - name: "api-server"
          image: "{{ include "clp.image.ref" . }}"
          imagePullPolicy: "{{ .Values.image.clpPackage.pullPolicy }}"
          env:
            - name: "CLP_DB_PASS"
              valueFrom:
                secretKeyRef:
                  name: {{ include "clp.fullname" . }}-database
                  key: "password"
            - name: "CLP_DB_USER"
              valueFrom:
                secretKeyRef:
                  name: {{ include "clp.fullname" . }}-database
                  key: "username"
            - name: "CLP_LOGS_DIR"
              value: "/var/log/api_server"
            - name: "RUST_LOG"
              value: "INFO"
          ports:
            - name: "api-server"
              containerPort: 3001
          volumeMounts:
            - name: {{ include "clp.volumeName" (dict
                "component_category" "api-server"
                "name" "logs"
              ) | quote }}
              mountPath: "/var/log/api_server"
            - name: "config"
              mountPath: "/etc/clp-config.yaml"
              subPath: "clp-config.yaml"
              readOnly: true
            {{- if eq .Values.clpConfig.stream_output.storage.type "fs" }}
            - name: {{ include "clp.volumeName" (dict
                "component_category" "shared-data"
                "name" "streams"
              ) | quote }}
              mountPath: "/var/data/streams"
            {{- end }}
          command: [
            "/opt/clp/bin/api_server",
            "--host", "0.0.0.0",
            "--port", "3001",
            "--config", "/etc/clp-config.yaml"
          ]
          readinessProbe:
            {{- include "clp.readinessProbeTimings" . | nindent 12 }}
            httpGet: &api-server-health-check
              path: "/health"
              port: "api-server"
          livenessProbe:
            {{- include "clp.livenessProbeTimings" . | nindent 12 }}
            httpGet: *api-server-health-check
      volumes:
        - {{- include "clp.pvcVolume" (dict
            "root" .
            "component_category" "api-server"
            "name" "logs"
          ) | nindent 10 }}
        - name: "config"
          configMap:
            name: {{ include "clp.fullname" . }}-config
        {{- if eq .Values.clpConfig.stream_output.storage.type "fs" }}
        - {{- include "clp.pvcVolume" (dict
            "root" .
            "component_category" "shared-data"
            "name" "streams"
          ) | nindent 10 }}
        {{- end }}
{{- end }}
