apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: {{ include "clp.fullname" . }}-compression-scheduler
  labels:
    {{- include "clp.labels" . | nindent 4 }}
    app.kubernetes.io/component: "compression-scheduler"
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "clp.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: "compression-scheduler"
  template:
    metadata:
      labels:
        {{- include "clp.labels" . | nindent 8 }}
        app.kubernetes.io/component: "compression-scheduler"
    spec:
      serviceAccountName: {{ include "clp.fullname" . }}-job-watcher
      terminationGracePeriodSeconds: 300
      securityContext:
        runAsUser: {{ .Values.securityContext.firstParty.uid }}
        runAsGroup: {{ .Values.securityContext.firstParty.gid }}
        fsGroup: {{ .Values.securityContext.firstParty.gid }}
      initContainers:
        {{- include "clp.waitFor" (dict "root" . "type" "job" "name" "db-table-creator") | nindent 8 }}
        {{- include "clp.waitFor" (dict "root" . "type" "service" "name" "queue") | nindent 8 }}
        {{- include "clp.waitFor" (dict "root" . "type" "service" "name" "redis") | nindent 8 }}
      containers:
        - name: "compression-scheduler"
          image: "{{ include "clp.image.ref" . }}"
          imagePullPolicy: "{{ .Values.image.clpPackage.pullPolicy }}"
          env:
            - name: "BROKER_URL"
              value: "amqp://{{ .Values.credentials.queue.username }}:{{ .Values.credentials.queue.password }}@{{ include "clp.fullname" . }}-queue:5672"
            - name: "CLP_DB_USER"
              valueFrom:
                secretKeyRef:
                  name: {{ include "clp.fullname" . }}-database
                  key: "username"
            - name: "CLP_DB_PASS"
              valueFrom:
                secretKeyRef:
                  name: {{ include "clp.fullname" . }}-database
                  key: "password"
            - name: "CLP_LOGGING_LEVEL"
              value: {{ .Values.clpConfig.compression_scheduler.logging_level | quote }}
            - name: "CLP_LOGS_DIR"
              value: "/var/log/compression_scheduler"
            - name: "PYTHONPATH"
              value: "/opt/clp/lib/python3/site-packages"
            - name: "RESULT_BACKEND"
              value: "redis://default:{{ .Values.credentials.redis.password }}@{{ include "clp.fullname" . }}-redis:6379/{{ .Values.clpConfig.redis.compression_backend_database }}"
          volumeMounts:
            - name: "config"
              mountPath: "/etc/clp-config.yaml"
              subPath: "clp-config.yaml"
              readOnly: true
            - name: "compression-scheduler-logs"
              mountPath: "/var/log/compression_scheduler"
            - name: "user-logs"
              mountPath: "/var/log/user"
            - name: "logs-input"
              mountPath: "/mnt/logs"
              readOnly: true
          command: [
            "python3", "-u",
            "-m", "job_orchestration.scheduler.compress.compression_scheduler",
            "--config", "/etc/clp-config.yaml"
          ]
      volumes:
        - name: "config"
          configMap:
            name: {{ include "clp.fullname" . }}-config
        - name: "compression-scheduler-logs"
          persistentVolumeClaim:
            claimName: {{ include "clp.fullname" . }}-compression-scheduler-logs
        - name: "user-logs"
          persistentVolumeClaim:
            claimName: {{ include "clp.fullname" . }}-user-logs
        - name: "logs-input"
          hostPath:
            path: "{{ .Values.clpConfig.logs_input.directory }}"
            type: "Directory"
