apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: {{ include "clp.fullname" . }}-compression-worker
  labels:
    {{- include "clp.labels" . | nindent 4 }}
    app.kubernetes.io/component: "compression-worker"
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "clp.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: "compression-worker"
  template:
    metadata:
      labels:
        {{- include "clp.labels" . | nindent 8 }}
        app.kubernetes.io/component: "compression-worker"
    spec:
      serviceAccountName: {{ include "clp.fullname" . }}-job-watcher
      terminationGracePeriodSeconds: 60
      securityContext:
        runAsUser: {{ .Values.securityContext.firstParty.uid }}
        runAsGroup: {{ .Values.securityContext.firstParty.gid }}
        fsGroup: {{ .Values.securityContext.firstParty.gid }}
      initContainers:
        {{- include "clp.waitFor" (dict "root" . "type" "service" "name" "queue") | nindent 8 }}
        {{- include "clp.waitFor" (dict "root" . "type" "service" "name" "redis") | nindent 8 }}
      containers:
        - name: "compression-worker"
          image: "{{ include "clp.image.ref" . }}"
          imagePullPolicy: "{{ .Values.image.clpPackage.pullPolicy }}"
          env:
            - name: "BROKER_URL"
              value: "amqp://{{ .Values.credentials.queue.username }}:{{ .Values.credentials.queue.password }}@{{ include "clp.fullname" . }}-queue:5672"
            - name: "CLP_CONFIG_PATH"
              value: "/etc/clp-config.yaml"
            - name: "CLP_HOME"
              value: "/opt/clp"
            - name: "CLP_LOGGING_LEVEL"
              value: {{ .Values.clpConfig.compression_worker.logging_level | quote }}
            - name: "CLP_LOGS_DIR"
              value: "/var/log/compression_worker"
            - name: "CLP_WORKER_LOG_PATH"
              value: "/var/log/compression_worker/worker.log"
            - name: "PYTHONPATH"
              value: "/opt/clp/lib/python3/site-packages"
            - name: "RESULT_BACKEND"
              value: "redis://default:{{ .Values.credentials.redis.password }}@{{ include "clp.fullname" . }}-redis:6379/{{ .Values.clpConfig.redis.compression_backend_database }}"
          volumeMounts:
            - name: "compression-worker-logs"
              mountPath: "/var/log/compression_worker"
            - name: "compression-worker-staged-archives"
              mountPath: "/var/data/staged-archives"
            - name: "compression-worker-tmp"
              mountPath: "/var/tmp"
            - name: "config"
              mountPath: "/etc/clp-config.yaml"
              subPath: "clp-config.yaml"
              readOnly: true
            - name: "logs-input"
              mountPath: "/mnt/logs"
              readOnly: true
            - name: "shared-data-archives"
              mountPath: "/var/data/archives"
          command: [
            "python3", "-u",
            "/opt/clp/lib/python3/site-packages/bin/celery",
            "-A", "job_orchestration.executor.compress",
            "worker",
            "--concurrency", "{{ .Values.workerConcurrency }}",
            "--loglevel", "WARNING",
            "-f", "/var/log/compression_worker/worker.log",
            "-Q", "compression",
            "-n", "compression-worker"
          ]
      volumes:
        {{- include "clp.pvcVolume" (dict
          "root" .
          "component" "compression-worker"
          "name" "logs"
        ) | nindent 8 }}
        {{- include "clp.pvcVolume" (dict
          "root" .
          "component" "compression-worker"
          "name" "staged-archives"
        ) | nindent 8 }}
        {{- include "clp.pvcVolume" (dict
          "root" .
          "component" "compression-worker"
          "name" "tmp"
        ) | nindent 8 }}
        {{- include "clp.pvcVolume" (dict
          "root" .
          "component" "shared-data"
          "name" "archives"
        ) | nindent 8 }}
        - name: "config"
          configMap:
            name: {{ include "clp.fullname" . }}-config
        - name: "logs-input"
          hostPath:
            path: "{{ .Values.clpConfig.logs_input.directory }}"
            type: "Directory"
