apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: {{ include "clp.fullname" . }}-query-worker
  labels:
    {{- include "clp.labels" . | nindent 4 }}
    app.kubernetes.io/component: "query-worker"
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "clp.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: "query-worker"
  template:
    metadata:
      labels:
        {{- include "clp.labels" . | nindent 8 }}
        app.kubernetes.io/component: "query-worker"
    spec:
      terminationGracePeriodSeconds: 60
      securityContext:
        runAsUser: {{ .Values.securityContext.firstParty.uid }}
        runAsGroup: {{ .Values.securityContext.firstParty.gid }}
        fsGroup: {{ .Values.securityContext.firstParty.gid }}
      containers:
        - name: "query-worker"
          image: "{{ include "clp.image.ref" . }}"
          imagePullPolicy: "{{ .Values.image.clpPackage.pullPolicy }}"
          env:
            - {{- include "clp.celeryBrokerUrlEnvVar" . | nindent 14 }}
            - {{- include "clp.celeryResultBackendEnvVar" (dict
                "root" .
                "database" .Values.clpConfig.redis.query_backend_database
              ) | nindent 14 }}
            - name: "CLP_CONFIG_PATH"
              value: "/etc/clp-config.yaml"
            - name: "CLP_HOME"
              value: "/opt/clp"
            - name: "CLP_LOGGING_LEVEL"
              value: {{ .Values.clpConfig.query_worker.logging_level | quote }}
            - name: "CLP_LOGS_DIR"
              value: "/var/log/query_worker"
            - name: "CLP_WORKER_LOG_PATH"
              value: "/var/log/query_worker/worker.log"
            - name: "PYTHONPATH"
              value: "/opt/clp/lib/python3/site-packages"
          volumeMounts:
            - name: "config"
              mountPath: "/etc/clp-config.yaml"
              subPath: "clp-config.yaml"
              readOnly: true
            - name: {{ include "clp.volumeName" (dict
                "component_category" "query-worker"
                "name" "logs"
              ) | quote }}
              mountPath: "/var/log/query_worker"
            - name: {{ include "clp.volumeName" (dict
                "component_category" "shared-data"
                "name" "archives"
              ) | quote }}
              mountPath: "/var/data/archives"
            - name: {{ include "clp.volumeName" (dict
                "component_category" "shared-data"
                "name" "streams"
              ) | quote }}
              mountPath: "/var/data/streams"
          command: [
            "python3", "-u",
            "/opt/clp/lib/python3/site-packages/bin/celery",
            "-A", "job_orchestration.executor.query",
            "worker",
            "--concurrency", "{{ .Values.workerConcurrency }}",
            "--loglevel", "WARNING",
            "-f", "/var/log/query_worker/worker.log",
            "-Q", "query",
            "-n", "query-worker"
          ]
      volumes:
        - {{- include "clp.pvcVolume" (dict
            "root" .
            "component_category" "query-worker"
            "name" "logs"
          ) | nindent 10 }}
        - {{- include "clp.pvcVolume" (dict
            "root" .
            "component_category" "shared-data"
            "name" "archives"
          ) | nindent 10 }}
        - {{- include "clp.pvcVolume" (dict
            "root" .
            "component_category" "shared-data"
            "name" "streams"
          ) | nindent 10 }}
        - name: "config"
          configMap:
            name: {{ include "clp.fullname" . }}-config
