apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: {{ include "clp-package.fullname" . }}-query-worker
  labels:
    {{- include "clp-package.labels" . | nindent 4 }}
    app.kubernetes.io/component: "query-worker"
spec:
  replicas: {{ .Values.workerConcurrency }}
  selector:
    matchLabels:
      {{- include "clp-package.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: "query-worker"
  template:
    metadata:
      labels:
        {{- include "clp-package.labels" . | nindent 8 }}
        app.kubernetes.io/component: "query-worker"
    spec:
      terminationGracePeriodSeconds: 60
      securityContext:
        runAsUser: {{ .Values.securityContext.firstParty.uid }}
        runAsGroup: {{ .Values.securityContext.firstParty.gid }}
        fsGroup: {{ .Values.securityContext.firstParty.gid }}
      initContainers:
        - name: "wait-for-queue"
          image: "busybox:latest"
          command: [
            "sh", "-c",
            "until nc -z {{ include "clp-package.fullname" . }}-queue 5672; do echo waiting for queue; sleep 2; done"
          ]
        - name: "wait-for-redis"
          image: "busybox:latest"
          command: [
            "sh", "-c",
            "until nc -z {{ include "clp-package.fullname" . }}-redis 6379; do echo waiting for redis; sleep 2; done"
          ]
      containers:
        - name: "query-worker"
          image: "{{ include "clp-package.image.ref" . }}"
          imagePullPolicy: "Always"
          env:
            - name: "BROKER_URL"
              value: "amqp://{{ .Values.credentials.queue.user }}:{{ .Values.credentials.queue.password }}@{{ include "clp-package.fullname" . }}-queue:5672"
            - name: "CLP_CONFIG_PATH"
              value: "/etc/clp-config.yml"
            - name: "CLP_HOME"
              value: "/opt/clp"
            - name: "CLP_LOGGING_LEVEL"
              value: {{ .Values.clpConfig.query_worker.logging_level | quote }}
            - name: "CLP_LOGS_DIR"
              value: "/var/log/query_worker"
            - name: "CLP_WORKER_LOG_PATH"
              value: "/var/log/query_worker/worker.log"
            - name: "PYTHONPATH"
              value: "/opt/clp/lib/python3/site-packages"
            - name: "RESULT_BACKEND"
              value: "redis://default:{{ .Values.credentials.redis.password }}@{{ include "clp-package.fullname" . }}-redis:6379/{{ .Values.clpConfig.redis.query_backend_database }}"
          volumeMounts:
            - name: "config"
              mountPath: "/etc/clp-config.yml"
              subPath: "clp-config.yml"
              readOnly: true
            - name: "query-worker-logs"
              mountPath: "/var/log/query_worker"
            - name: "archives"
              mountPath: "/var/data/archives"
            - name: "staged-streams"
              mountPath: "/var/data/staged-streams"
            - name: "streams"
              mountPath: "/var/data/streams"
          command: [
            "python3", "-u",
            "/opt/clp/lib/python3/site-packages/bin/celery",
            "-A", "job_orchestration.executor.query",
            "worker",
            "--concurrency", "{{ .Values.workerConcurrency }}",
            "--loglevel", "WARNING",
            "-f", "/var/log/query_worker/worker.log",
            "-Q", "query",
            "-n", "query-worker"
          ]
      volumes:
        - name: "config"
          configMap:
            name: {{ include "clp-package.fullname" . }}-config
        - name: "query-worker-logs"
          persistentVolumeClaim:
            claimName: {{ include "clp-package.fullname" . }}-query-worker-logs
        - name: "archives"
          hostPath:
            path: {{ include "clp-package.dataDirHost" . }}/archives
            type: "DirectoryOrCreate"
        - name: "staged-streams"
          hostPath:
            path: {{ include "clp-package.dataDirHost" . }}/staged-streams
            type: "DirectoryOrCreate"
        - name: "streams"
          persistentVolumeClaim:
            claimName: {{ include "clp-package.fullname" . }}-streams
---
apiVersion: "v1"
kind: "PersistentVolumeClaim"
metadata:
  name: {{ include "clp-package.fullname" . }}-query-worker-logs
  labels:
    {{- include "clp-package.labels" . | nindent 4 }}
    app.kubernetes.io/component: "query-worker"
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: "local-storage"
  selector:
    matchLabels:
      {{- include "clp-package.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: "query-worker"
  resources:
    requests:
      storage: "5Gi"
