apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: {{ include "clp.fullname" . }}-reducer
  labels:
    {{- include "clp.labels" . | nindent 4 }}
    app.kubernetes.io/component: "reducer"
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "clp.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: "reducer"
  template:
    metadata:
      labels:
        {{- include "clp.labels" . | nindent 8 }}
        app.kubernetes.io/component: "reducer"
    spec:
      hostname: {{ include "clp.fullname" . }}-reducer
      subdomain: {{ include "clp.fullname" . }}-reducer
      terminationGracePeriodSeconds: 10
      securityContext:
        runAsUser: {{ .Values.securityContext.firstParty.uid }}
        runAsGroup: {{ .Values.securityContext.firstParty.gid }}
        fsGroup: {{ .Values.securityContext.firstParty.gid }}
      initContainers:
        - name: "wait-for-query-scheduler"
          image: "busybox:latest"
          command:
            - "sh"
            - "-c"
            - >-
              until nc -z {{ include "clp.fullname" . }}-query-scheduler 7000;
                do echo Waiting for query-scheduler to be ready...;
                sleep 2;
              done
        - name: "wait-for-results-cache"
          image: "busybox:latest"
          command:
            - "sh"
            - "-c"
            - >-
              until nc -z {{ include "clp.fullname" . }}-results-cache 27017;
                do echo Waiting for results-cache to be ready...;
                sleep 2;
              done
      containers:
        - name: "reducer"
          image: "{{ include "clp.image.ref" . }}"
          imagePullPolicy: "Always"
          env:
            - name: "CLP_HOME"
              value: "/opt/clp"
            - name: "CLP_LOGGING_LEVEL"
              value: {{ .Values.clpConfig.reducer.logging_level | quote }}
            - name: "CLP_LOGS_DIR"
              value: "/var/log/reducer"
            - name: "PYTHONPATH"
              value: "/opt/clp/lib/python3/site-packages"
          volumeMounts:
            - name: "config"
              mountPath: "/etc/clp-config.yaml"
              subPath: "clp-config.yaml"
              readOnly: true
            - name: "reducer-logs"
              mountPath: "/var/log/reducer"
          command: [
            "python3", "-u",
            "-m", "job_orchestration.reducer.reducer",
            "--config", "/etc/clp-config.yaml",
            "--concurrency", "{{ .Values.workerConcurrency }}",
            "--upsert-interval", "{{ .Values.clpConfig.reducer.upsert_interval }}"
          ]
      volumes:
        - name: "config"
          configMap:
            name: {{ include "clp.fullname" . }}-config
        - name: "reducer-logs"
          persistentVolumeClaim:
            claimName: {{ include "clp.fullname" . }}-reducer-logs
