apiVersion: "v1"
kind: "Service"
metadata:
  name: {{ include "clp-package.fullname" . }}-webui
  labels:
    {{- include "clp-package.labels" . | nindent 4 }}
    app.kubernetes.io/component: "webui"
spec:
  type: "NodePort"
  selector:
    {{- include "clp-package.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: "webui"
  ports:
    - port: 4000
      targetPort: 4000
      nodePort: 30400
---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: {{ include "clp-package.fullname" . }}-webui
  labels:
    {{- include "clp-package.labels" . | nindent 4 }}
    app.kubernetes.io/component: "webui"
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "clp-package.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: "webui"
  template:
    metadata:
      labels:
        {{- include "clp-package.labels" . | nindent 8 }}
        app.kubernetes.io/component: "webui"
    spec:
      terminationGracePeriodSeconds: 60
      securityContext:
        runAsUser: {{ .Values.securityContext.firstParty.uid }}
        runAsGroup: {{ .Values.securityContext.firstParty.gid }}
        fsGroup: {{ .Values.securityContext.firstParty.gid }}
      initContainers:
        - name: "wait-for-database"
          image: "busybox:latest"
          command: [
            "sh", "-c",
            "until nc -z {{ include "clp-package.fullname" . }}-database 3306; do echo waiting for database; sleep 2; done"
          ]
        - name: "wait-for-results-cache"
          image: "busybox:latest"
          command: [
            "sh", "-c",
            "until nc -z {{ include "clp-package.fullname" . }}-results-cache 27017; do echo waiting for results-cache; sleep 2; done"
          ]
      containers:
        - name: "webui"
          image: "{{ include "clp-package.image.ref" . }}"
          imagePullPolicy: "Always"
          env:
            - name: "CLP_DB_USER"
              valueFrom:
                secretKeyRef:
                  name: {{ include "clp-package.fullname" . }}-secret
                  key: "db-username"
            - name: "CLP_DB_PASS"
              valueFrom:
                secretKeyRef:
                  name: {{ include "clp-package.fullname" . }}-secret
                  key: "db-password"
            - name: "HOST"
              value: "0.0.0.0"
            - name: "NODE_ENV"
              value: "production"
            - name: "NODE_PATH"
              value: "/opt/clp/var/www/webui/server/node_modules"
            - name: "PORT"
              value: "4000"
            - name: "RATE_LIMIT"
              value: "1000"
          ports:
            - containerPort: 4000
          volumeMounts:
            - name: "client-settings"
              mountPath: "/opt/clp/var/www/webui/client/settings.json"
              subPath: "webui-client-settings.json"
              readOnly: true
            - name: "server-settings"
              mountPath: "/opt/clp/var/www/webui/server/dist/settings.json"
              subPath: "webui-server-settings.json"
              readOnly: true
            - name: "streams"
              mountPath: "/var/data/streams"
          command: [
            "/opt/clp/bin/node-22",
            "/opt/clp/var/www/webui/server/dist/src/main.js"
          ]
          livenessProbe:
            {{- include "clp-package.livenessProbeTimings" . | nindent 12 }}
            tcpSocket:
              port: 4000
          readinessProbe:
            {{- include "clp-package.readinessProbeTimings" . | nindent 12 }}
            tcpSocket:
              port: 4000
      volumes:
        - name: "client-settings"
          configMap:
            name: {{ include "clp-package.fullname" . }}-config
        - name: "server-settings"
          configMap:
            name: {{ include "clp-package.fullname" . }}-config
        - name: "streams"
          persistentVolumeClaim:
            claimName: {{ include "clp-package.fullname" . }}-streams
---
apiVersion: "v1"
kind: "PersistentVolumeClaim"
metadata:
  name: {{ include "clp-package.fullname" . }}-streams
  labels:
    {{- include "clp-package.labels" . | nindent 4 }}
    app.kubernetes.io/component: "streams"
spec:
  accessModes: ["ReadWriteMany"]
  storageClassName: "local-storage"
  selector:
    matchLabels:
      {{- include "clp-package.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: "streams"
  resources:
    requests:
      storage: "20Gi"
