name: "clp-rust-checks"

on:
  pull_request:
    paths: &monitored_paths
      - ".cargo/**"
      - "Cargo.lock"
      - "Cargo.toml"
      - ".github/workflows/clp-rust-checks.yaml"
      - "components/api-server/**"
      - "components/clp-rust-utils/**"
      - "components/log-ingestor/**"
      - "taskfile.yaml"
      - "taskfiles/**"
      - "tools/scripts/localstack/**"
  push:
    paths: *monitored_paths
  schedule:
    # Run daily at 00:15 UTC (the 15 is to avoid periods of high load)
    - cron: "15 0 * * *"
  workflow_dispatch:

concurrency:
  group: "${{github.workflow}}-${{github.ref}}"
  # Cancel in-progress jobs for efficiency
  cancel-in-progress: true

jobs:
  rust-checks:
    runs-on: "ubuntu-22.04"
    steps:
      - uses: "actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683"
        with:
          submodules: "recursive"

      - name: "Install task"
        shell: "bash"
        run: "npm install -g @go-task/cli@3.48.0"

      - name: "Install the latest version of uv"
        uses: "astral-sh/setup-uv@85856786d1ce8acfbcc2f13a5f3fbd6b938f9f41"  # v7.1.2

      - name: "Validate lock files"
        shell: "bash"
        run: "task deps:lock:check-rust"

      - name: "Lint"
        shell: "bash"
        run: "task lint:check-rust"

      - name: "Test"
        shell: "bash"
        run: "task tests:rust-all"
