name: generate-build-dependency-image

on:
  push:
    paths:
      - '.github/workflows/clp-dependency-image-build.yaml'
      - 'components/core/tools/docker-images/**'
      - 'components/core/tools/scripts/lib_install/**'
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME_BASE: ${{github.repository}}/clp-core-dependencies-x86

concurrency: build-${{github.ref}}

jobs:
  focal:
    concurrency:
      group: ${{github.workflow}}-focal-${{github.ref}}
      cancel-in-progress: true
    runs-on: ubuntu-20.04
    name: Build Image - Ubuntu Focal
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
            submodules: recursive

      - name: Workaround actions/runner-images/issues/6775
        run: chown $(id -u):$(id -g) -R .

      - name: Filter relevant changes
        uses: dorny/paths-filter@v2
        id: filter
        with:
          # Consider changes between the previous commit and this one
          base: ${{ github.ref_name }}
          filters: |
            src:
              - '.github/workflows/clp-dependency-image-build.yaml'
              - 'components/core/tools/docker-images/clp-env-base-focal/**'
              - 'components/core/tools/scripts/lib_install/*.sh'
              - 'components/core/tools/scripts/lib_install/ubuntu-focal/**'
    
      - name: Build and Push Ubuntu Focal Docker Image
        uses: ./.github/actions/clp-docker-build-push-action
        if: steps.filter.outputs.src == 'true'
        with:
          image_name: ${{env.IMAGE_NAME_BASE}}-ubuntu-focal
          context: components/core/
          file: components/core/tools/docker-images/clp-env-base-focal/Dockerfile
          token: ${{secrets.GITHUB_TOKEN}}
          push_image: ${{'pull_request' != github.event_name && 'refs/heads/main' == github.ref}}

  bionic:
    concurrency:
      group: ${{github.workflow}}-bionic-${{github.ref}}
      cancel-in-progress: true
    runs-on: ubuntu-20.04
    name: Build Image - Ubuntu Bionic
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
            submodules: recursive

      - name: Workaround actions/runner-images/issues/6775
        run: chown $(id -u):$(id -g) -R .

      - name: Filter relevant changes
        uses: dorny/paths-filter@v2
        id: filter
        with:
          # Consider changes between the previous commit and this one
          base: ${{ github.ref_name }}
          filters: |
            src:
              - '.github/workflows/clp-dependency-image-build.yaml'
              - 'components/core/tools/docker-images/clp-env-base-bionic/**'
              - 'components/core/tools/scripts/lib_install/*.sh'
              - 'components/core/tools/scripts/lib_install/ubuntu-bionic/**'

      - name: Build and Push Ubuntu Bionic Docker Image
        uses: ./.github/actions/clp-docker-build-push-action
        if: steps.filter.outputs.src == 'true'
        with:
          image_name: ${{env.IMAGE_NAME_BASE}}-ubuntu-bionic
          context: components/core/
          file: components/core/tools/docker-images/clp-env-base-bionic/Dockerfile
          token: ${{secrets.GITHUB_TOKEN}}
          push_image: ${{'pull_request' != github.event_name && 'refs/heads/main' == github.ref}}

  centos:
    concurrency:
      group: ${{github.workflow}}-centos-${{github.ref}}
      cancel-in-progress: true
    runs-on: ubuntu-20.04
    name: Build Image - CentOS 7.4
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
            submodules: recursive

      - name: Workaround actions/runner-images/issues/6775
        run: chown $(id -u):$(id -g) -R .

      - name: Filter relevant changes
        uses: dorny/paths-filter@v2
        id: filter
        with:
          # Consider changes between the previous commit and this one
          base: ${{ github.ref_name }}
          filters: |
            src:
              - '.github/workflows/clp-dependency-image-build.yaml'
              - 'components/core/tools/docker-images/clp-env-base-centos7.4/**'
              - 'components/core/tools/scripts/lib_install/*.sh'
              - 'components/core/tools/scripts/lib_install/ubuntu-centos7.4/**'

      - name: Build and Push Centos7.4 Docker Image
        uses: ./.github/actions/clp-docker-build-push-action
        if: steps.filter.outputs.src == 'true'
        with:
          image_name: ${{env.IMAGE_NAME_BASE}}-centos7.4
          context: components/core/
          file: components/core/tools/docker-images/clp-env-base-centos7.4/Dockerfile
          token: ${{secrets.GITHUB_TOKEN}}
          push_image: ${{'pull_request' != github.event_name && 'refs/heads/main' == github.ref}}
