name: "clp-pr-title-checks"

on:
  pull_request_target:
    types: ["edited", "opened", "reopened"]
    branches: ["main"]

permissions:
  pull-requests: "read"

concurrency:
  group: "${{github.workflow}}-${{github.ref}}"

  # Cancel in-progress jobs for efficiency
  cancel-in-progress: true

jobs:
  conventional-commits:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "amannn/action-semantic-pull-request@v5"
        env:
          GITHUB_TOKEN: "${{secrets.GITHUB_TOKEN}}"
