name: generate-build-dependency-image

on:
  push:
    branches: ['main']
    paths:
      - 'components/core/tools/docker-images/**'
      - 'components/core/tools/scripts/lib_install/**'
      - '.github/workflows/clp-dependency-image-build.yaml'
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME_BASE: ${{github.repository}}/clp-core-dependencies-x86

concurrency: build-${{github.ref}} 

jobs:
  build:
    runs-on: ubuntu-20.04
    name: Build Image
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Log in to the Github Packages Container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
    
      - name: Build and Push Ubuntu Focal Docker Image
        uses: ./.github/actions/clp-docker-build-push-action
        with:
          image_name: ${{env.IMAGE_NAME_BASE}}-ubuntu-focal
          context: components/core/
          file: components/core/tools/docker-images/clp-env-base-focal/Dockerfile

      - name: Build and Push Ubuntu Bionic Docker Image
        uses: ./.github/actions/clp-docker-build-push-action
        with:
          image_name: ${{env.IMAGE_NAME_BASE}}-ubuntu-bionic
          context: components/core/
          file: components/core/tools/docker-images/clp-env-base-bionic/Dockerfile


      - name: Build and Push Centos7.4 Docker Image
        uses: ./.github/actions/clp-docker-build-push-action
        with:
          image_name: ${{env.IMAGE_NAME_BASE}}-centos7.4
          context: components/core/
          file: components/core/tools/docker-images/clp-env-base-centos7.4/Dockerfile
